receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Add resource attributes for better analysis
  resource:
    attributes:
      - key: environment
        value: "development"
        action: upsert
      - key: service.name
        value: "claude-code-devcontainer"
        action: upsert
  
  batch:
    timeout: 10s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    
  debug:
    verbosity: normal

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  
  pprof:
    endpoint: 0.0.0.0:1777

service:
  extensions: [health_check, pprof]
  
  pipelines:
    metrics: 
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus, debug]
    
    logs:    
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [debug, loki]
